/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ChartLabRouteImport } from './routes/chart-lab'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTransactionsIndexRouteImport } from './routes/_authenticated/transactions/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSavingsIndexRouteImport } from './routes/_authenticated/savings/index'
import { Route as AuthenticatedDebtsIndexRouteImport } from './routes/_authenticated/debts/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './routes/_authenticated/categories/index'
import { Route as AuthenticatedBudgetsIndexRouteImport } from './routes/_authenticated/budgets/index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics/index'
import { Route as AuthenticatedAccountsIndexRouteImport } from './routes/_authenticated/accounts/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'

const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartLabRoute = ChartLabRouteImport.update({
  id: '/chart-lab',
  path: '/chart-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionsIndexRoute =
  AuthenticatedTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSavingsIndexRoute =
  AuthenticatedSavingsIndexRouteImport.update({
    id: '/savings/',
    path: '/savings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebtsIndexRoute = AuthenticatedDebtsIndexRouteImport.update({
  id: '/debts/',
  path: '/debts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBudgetsIndexRoute =
  AuthenticatedBudgetsIndexRouteImport.update({
    id: '/budgets/',
    path: '/budgets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountsIndexRoute =
  AuthenticatedAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/chart-lab': typeof ChartLabRoute
  '/help': typeof HelpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signout': typeof SignoutRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/budgets/': typeof AuthenticatedBudgetsIndexRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/debts/': typeof AuthenticatedDebtsIndexRoute
  '/savings/': typeof AuthenticatedSavingsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/chart-lab': typeof ChartLabRoute
  '/help': typeof HelpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signout': typeof SignoutRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/accounts': typeof AuthenticatedAccountsIndexRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/budgets': typeof AuthenticatedBudgetsIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/debts': typeof AuthenticatedDebtsIndexRoute
  '/savings': typeof AuthenticatedSavingsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/transactions': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/chart-lab': typeof ChartLabRoute
  '/help': typeof HelpRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signout': typeof SignoutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/accounts/': typeof AuthenticatedAccountsIndexRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/budgets/': typeof AuthenticatedBudgetsIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/debts/': typeof AuthenticatedDebtsIndexRoute
  '/_authenticated/savings/': typeof AuthenticatedSavingsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/transactions/': typeof AuthenticatedTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart-lab'
    | '/help'
    | '/sign-in'
    | '/sign-up'
    | '/signout'
    | '/settings/notifications'
    | '/accounts/'
    | '/analytics/'
    | '/budgets/'
    | '/categories/'
    | '/debts/'
    | '/savings/'
    | '/settings/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chart-lab'
    | '/help'
    | '/sign-in'
    | '/sign-up'
    | '/signout'
    | '/'
    | '/settings/notifications'
    | '/accounts'
    | '/analytics'
    | '/budgets'
    | '/categories'
    | '/debts'
    | '/savings'
    | '/settings'
    | '/transactions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/chart-lab'
    | '/help'
    | '/sign-in'
    | '/sign-up'
    | '/signout'
    | '/_authenticated/'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/accounts/'
    | '/_authenticated/analytics/'
    | '/_authenticated/budgets/'
    | '/_authenticated/categories/'
    | '/_authenticated/debts/'
    | '/_authenticated/savings/'
    | '/_authenticated/settings/'
    | '/_authenticated/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ChartLabRoute: typeof ChartLabRoute
  HelpRoute: typeof HelpRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SignoutRoute: typeof SignoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-lab': {
      id: '/chart-lab'
      path: '/chart-lab'
      fullPath: '/chart-lab'
      preLoaderRoute: typeof ChartLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transactions/': {
      id: '/_authenticated/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthenticatedTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/savings/': {
      id: '/_authenticated/savings/'
      path: '/savings'
      fullPath: '/savings/'
      preLoaderRoute: typeof AuthenticatedSavingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debts/': {
      id: '/_authenticated/debts/'
      path: '/debts'
      fullPath: '/debts/'
      preLoaderRoute: typeof AuthenticatedDebtsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/budgets/': {
      id: '/_authenticated/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof AuthenticatedBudgetsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts/': {
      id: '/_authenticated/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedAccountsIndexRoute: typeof AuthenticatedAccountsIndexRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedBudgetsIndexRoute: typeof AuthenticatedBudgetsIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedDebtsIndexRoute: typeof AuthenticatedDebtsIndexRoute
  AuthenticatedSavingsIndexRoute: typeof AuthenticatedSavingsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTransactionsIndexRoute: typeof AuthenticatedTransactionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedAccountsIndexRoute: AuthenticatedAccountsIndexRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedBudgetsIndexRoute: AuthenticatedBudgetsIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedDebtsIndexRoute: AuthenticatedDebtsIndexRoute,
  AuthenticatedSavingsIndexRoute: AuthenticatedSavingsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTransactionsIndexRoute: AuthenticatedTransactionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ChartLabRoute: ChartLabRoute,
  HelpRoute: HelpRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SignoutRoute: SignoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
